Notices first steps
GoIT-Final-Project/your-pet-backend pull request #5
Opened 2023-07-22 11:11 UTC by Butcherok

worked - controllers addPet % getAll with out user.id

2023-07-22 13:01 UTC, vnko1 requested changes
-створити ендпоінт для пошуку з урахуванням переданих параметрів в NoticesSearch та категоріям (NoticesCategoriesNav).
пошуку оголошеннь по заголовку, якщо був передан тільки заголовок або по категоріям, якщо була передана тільки категорія. Якщо було передан заголовок і категорія, то щоб робилась загальна вибірка по заголовку і категорії

-створити ендпоінт для отримання одного оголошення

2023-07-25 18:48 UTC, vnko1 requested changes

2023-07-25 18:48 UTC, vnko1 commented on routes/notices/noticesRoute.js
> +	fieldValidation(editUserValidation, schemaMessage.auth),
зачем здесь fieldValidation и схема валидации для юзера?

2023-07-25 18:48 UTC, vnko1 commented on routes/notices/noticesRoute.js
> +	fieldValidation(editUserValidation, schemaMessage.auth),
зачем здесь fieldValidation и схема валидации для юзера?

2023-07-25 18:48 UTC, vnko1 commented on routes/notices/noticesRoute.js
> +	checkPetData,
CheckPetData нужно переименовать на общее название метода. В миддлваре я сам переименую, ты переименуй только в своей части кода

2023-07-25 18:48 UTC, vnko1 commented on routes/notices/noticesRoute.js
> +	isValidIdNotice,
isValidId, isValidIdNotice делают то же самое, тут нужно сделать 1 функцию, через декорирование

2023-07-25 18:48 UTC, vnko1 commented on app.js
> +	noticesRouter,
переименуй везде название, что б было одинаково - в "noticesRoute"

2023-07-25 18:48 UTC, vnko1 commented on models/notice/noticeModel.js
> +const { date } = require("joi");
нужно удалить, если не используется

2023-07-25 18:48 UTC, vnko1 commented on models/notice/noticeModel.js
> +			maxlength: 15,
по ТЗ должно быть не больше 16

2023-07-25 18:48 UTC, vnko1 commented on models/notice/noticeModel.js
> +		type: {
по тз єто поле required

2023-07-25 18:48 UTC, vnko1 commented on models/notice/noticeModel.js
> +			type: String,
по ТЗ длинна символов в комментарии должно быть не более 120

2023-07-25 18:48 UTC, vnko1 commented on models/notice/noticeModel.js
> +		location: {
По ТЗ это поле обязательно, required:true

2023-07-25 18:48 UTC, vnko1 commented on models/notice/noticeModel.js
> +		price: {
По ТЗ это поле обязательно, required:true, тут можно Integer вместо намбер и по тз, число должно быть >0

2023-07-25 18:48 UTC, vnko1 commented on schema/notices/noticesSchemaValidation.js
> +		.min(2)
В локейшн нету ограничений по количеству символов

2023-07-25 18:48 UTC, vnko1 commented on schema/notices/noticesSchemaValidation.js
> +	favorite: Joi.boolean,
нужно ли сейчас это поле

2023-07-25 18:48 UTC, vnko1 commented on services/notices/noticesService.js
> +		search = "",
переименуй на filter, что б было уже одинаково с новостями.

2023-07-25 18:48 UTC, vnko1 commented on services/notices/noticesService.js
> +		const total = await Notice.count(findOptions);
метод каунт deprecated, поменяй на countDocuments

2023-07-25 18:48 UTC, vnko1 commented on services/notices/noticesService.js
> +					$or: [{ title: { $regex: search, $options: "i" } }],
что у тебя будет хранится в тайтле, если по ТЗ такого поля нету, и соответсвенно что будет искать 
<img width="622" alt="Знімок екрана 2023-07-25 о 21 10 14" src="https://github.com/GoIT-Final-Project/your-pet-backend/assets/102794464/41b2671c-5ba2-4e89-a14e-3fa422571526">

2023-07-25 18:48 UTC, vnko1 commented on services/notices/noticesService.js
> +		const total = await User.count(id);
метод каунт deprecated, поменяй на countDocuments

2023-07-25 18:48 UTC, vnko1 commented on services/notices/noticesService.js
> +		const total = await Notice.count({ owner });
метод каунт deprecated, поменяй на countDocuments

2023-07-25 18:48 UTC, vnko1 commented on services/notices/noticesService.js
> +	static changeUserFavorites(id, data) {
используй из usersService.js метод что на картинке, что б не дублировался код. если использовать его, то changeUserFavorites вообще не нужен в этом классе, а сразу вызывать в контроллере
<img width="622" alt="Знімок екрана 2023-07-25 о 21 13 22" src="https://github.com/GoIT-Final-Project/your-pet-backend/assets/102794464/7b2787e0-698b-4ae5-8be7-a6d94bc64ec7">
<img width="622" alt="1" src="https://github.com/GoIT-Final-Project/your-pet-backend/assets/102794464/4c54dbb4-f921-49a6-889c-eb0be13c9470">

2023-07-25 18:48 UTC, vnko1 commented on services/notices/noticesService.js
> +	static async findOwnerFavNotices({}) {
этот метод лучше перенести в usersService.js и использовать в контроллере из класса юзера, а не тут.  я добавлю, а ты потом импортируешь куда нужно

2023-07-25 18:48 UTC, vnko1 commented on temp/file_2GfqrplRj5FzGmWFA0Jj0.png
удали файл из темп

2023-07-25 18:48 UTC, vnko1 commented on middlewares/isValidIdNotice.js
это метод и isValidId сделать универсальным. через декоратор, я сделаю

2023-07-25 18:48 UTC, vnko1 commented on controllers/notices/noticesController.js
> +	res.status(201).json(response);
думаешь лучше здесь 201, я просто везде уже ставил 200, давай может 200 лучше ошибку, что б было уже одинаково?

2023-07-25 18:48 UTC, vnko1 commented on controllers/notices/noticesController.js
В res.json давать писать что б было одинаково: res.json({notices,?total}) 
res.json({data:notices,?total}) или res.json({notices, ?total})

2023-07-25 18:48 UTC, vnko1 commented on controllers/notices/noticesController.js
> +	const { page, limit, sort, search, category } = req.query;
search переименуй на filter

2023-07-25 18:48 UTC, vnko1 commented on controllers/notices/noticesController.js
> +	res.json(result);
res.json({data:notices,?total}) или res.json({notices, ?total})

2023-07-25 18:48 UTC, vnko1 commented on controllers/notices/noticesController.js
> +	res.json(updatedNotice);
res.json({data:updateStatus}) или res.json({notices:updateStatus})

2023-07-25 18:48 UTC, vnko1 commented on controllers/notices/noticesController.js
> +	res.json({ message: "Notice deleted" });
давай вместо мсж, ід присилать

2023-07-25 18:48 UTC, vnko1 commented on controllers/notices/noticesController.js
> +	const updatedStatus = await Notices.changeUserFavorites(
тут нужно будет использовать универсальный метод из юзерсервис, я его сделаю

2023-07-25 18:48 UTC, vnko1 commented on controllers/notices/noticesController.js
> +	res.json(updatedStatus);
res.json({data:updateStatus})
или res.json({notices, ?total})

2023-07-25 18:48 UTC, vnko1 commented on controllers/notices/noticesController.js
> +	res.json(updatedStatus);
res.json({data:updateStatus})
или res.json({notices, ?total})

2023-07-25 18:53 UTC, vnko1 requested changes
Тз для @Butcherok: 
- прочитать комменты в код ревью;
-  DELETE /:noticeId - не работает, в юрл передаю ид карточки, в ответ приходит Bad request! Missing required name field or wrong field name. Еще, тебе нужно предусмотреть функционал, который запрещал бы возможность удаления обьявления юзера, другим юзером.
-  устранить кофликты


ТЗ для @vnko1 :
isValidId, isValidIdNotice делают то же самое, тут нужно сделать 1 функцию, через декорирование

CheckPetData нужно переименовать на общее название метода. В миддлваре я сам переименую, ты переименуй только в своей части кода

этот метод лучше перенести в usersService.js и использовать в контроллере из класса юзера, а не тут. я добавлю, а ты потом импортируешь куда нужно
findOwnerFavNotices({})

2023-07-25 20:07 UTC, vnko1 requested changes

2023-07-25 20:07 UTC, vnko1 commented on services/notices/noticesService.js
> +					$or: [{ title: { $regex: search, $options: "i" } }],
может еще добавит возможность поиска по комментариям?

2023-07-25 20:07 UTC, vnko1 commented on app.js
из ответов бека убери лишние поля через projection

2023-07-25 20:07 UTC, vnko1 commented on controllers/notices/noticesController.js
> +	const result = await Notices.deleteNotice(noticeId);
не нашел этого метода в классе

2023-07-26 04:32 UTC, vnko1 requested changes

2023-07-26 04:32 UTC, vnko1 commented on models/user/userModel.js
> +				unique: true,
Тут убери уник

2023-07-26 08:36 UTC, Butcherok commented on models/notice/noticeModel.js
> +		price: {
Все эти проверки идут в ДЖОЙ схеме. Нужно ли их дублировать? Мы вроде беседовали на эту тему в самом начале и решили что в ДЖОЙ всё проверяем. иди нет?

2023-07-26 09:51 UTC, vnko1 commented on routes/notices/noticesRoute.js
> +	isValidIdNotice,
єта часть не исправлена

2023-07-26 10:24 UTC, vnko1 requested changes

2023-07-26 10:24 UTC, vnko1 commented on controllers/notices/noticesController.js
частично исправлено

2023-07-26 10:24 UTC, vnko1 commented on controllers/notices/noticesController.js
> +	res.status(201).json(response);
не исправлено

2023-07-26 10:24 UTC, vnko1 commented on controllers/notices/noticesController.js
> +	if (!notice) {
в коде подсвечивается: Could not find name 'notice'. Did you mean 'notices'?ts(2570)
any

2023-07-26 10:24 UTC, vnko1 commented on models/notice/noticeModel.js
> +		price: {
не помню, но на занятиях говорили что лучше ставить валидацию и в джой и в схеме

2023-07-26 10:24 UTC, vnko1 commented on controllers/notices/noticesController.js
> +	const updatedStatus = await Notices.changeUserFavorites(
етот метод принимает обьект в качевстве аргумента, а ти просто передаеш параметри, {
			new: true,
		} - никак не обрабативается

2023-07-26 22:03 UTC, vnko1 approved these changes

2023-07-26 22:04 UTC, vnko1 requested changes
del

2023-07-26 22:18 UTC, vnko1 approved these changes

2023-07-26 22:19 UTC, merged